import { TypescaleConfig } from '@angularity/theming-material';

const font = `Roboto`;

export const APP_THEME_TYPESCALES: TypescaleConfig[] = [
  {
    name: 'display-large',
    font,
    weight: '400',
    size: '57px',
    lineHeight: '112.28%',
    tracking: '-0.2px',
  },
  {
    name: 'display-medium',
    font,
    weight: '400',
    size: '45px',
    lineHeight: '115.56%',
    tracking: '0.0px',
  },
  {
    name: 'display-small',
    font,
    weight: '400',
    size: '36px',
    lineHeight: '122.22%',
    tracking: '0.0px',
  },
  {
    name: 'headline-large',
    font,
    weight: '400',
    size: '32px',
    lineHeight: '125%',
    tracking: '0.0px',
  },
  {
    name: 'headline-medium',
    font,
    weight: '400',
    size: '28px',
    lineHeight: '128.57%',
    tracking: '0.0px',
  },
  {
    name: 'headline-small',
    font,
    weight: '400',
    size: '24px',
    lineHeight: '133.33%',
    tracking: '0.0px',
  },
  {
    name: 'title-large',
    font,
    weight: '400',
    size: '22px',
    lineHeight: '127.27%',
    tracking: '0.0px',
  },
  {
    name: 'title-medium',
    font,
    weight: '500',
    size: '16px',
    lineHeight: '150%',
    tracking: '0.2px',
  },
  {
    name: 'title-small',
    font,
    weight: '500',
    size: '14px',
    lineHeight: '142.86%',
    tracking: '0.1px',
  },
  {
    name: 'body-large',
    font,
    weight: '400',
    size: '16px',
    lineHeight: '150%',
    tracking: '0.5px',
  },
  {
    name: 'body-medium',
    font,
    weight: '400',
    size: '14px',
    lineHeight: '142.86%',
    tracking: '0.2px',
  },
  {
    name: 'body-small',
    font,
    weight: '400',
    size: '12px',
    lineHeight: '133.33%',
    tracking: '0.4px',
  },
  {
    name: 'label-large',
    font,
    weight: '500',
    size: '14px',
    lineHeight: '142.86%',
    tracking: '0.1px',
  },
  {
    name: 'label-medium',
    font,
    weight: '500',
    size: '12px',
    lineHeight: '133.33%',
    tracking: '0.5px',
  },
  {
    name: 'label-small',
    font,
    weight: '500',
    size: '11px',
    lineHeight: '145.45%',
    tracking: '0.5px',
  },
];
